### ISSUE TITLE
Add user class to config?

### ISSUE THREAD

**Issue by shredder-rull** [ledermann/drafting#1]
Hello!
We have a little problem with integration this gem in our system. Our users class is CMS::User and we have an error:

```
Exception: NameError: uninitialized constant Draft::User
--
 0: /home/shredder/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/inheritance.rb:158:in `compute_type'
 1: /home/shredder/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/reflection.rb:271:in `compute_class'
 2: /home/shredder/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/reflection.rb:267:in `klass'
 3: /home/shredder/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/associations/association.rb:214:in `raise_on_type_mismatch!'
 4: /home/shredder/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/associations/belongs_to_association.rb:12:in `replace'
```

Could you fix it? Thanks.

**Comment by ledermann** [comment]
You can fix it by yourself. Just add this code to an initializer:

```ruby
Draft.belongs_to :user, class_name: 'CMS::User'
```
