### ISSUE TITLE
uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Identity

### ISSUE THREAD

**Issue by amit-natani** [ledermann/drafting#4]
I have upgraded my application to rails 4.2.9.
Now when I try to restore any saved draft then it throws following error:

NameError - uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Identity:
  activesupport (4.2.9) lib/active_support/dependencies.rb:533:in `load_missing_constant'
  activesupport (4.2.9) lib/active_support/dependencies.rb:184:in `const_missing'
  activesupport (4.2.9) lib/active_support/inflector/methods.rb:276:in `block in constantize'
  activesupport (4.2.9) lib/active_support/inflector/methods.rb:259:in `constantize'
  activesupport (4.2.9) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
  activesupport (4.2.9) lib/active_support/core_ext/marshal.rb:10:in `rescue in load_with_autoloading'
  activesupport (4.2.9) lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
  drafting (0.2.0) lib/drafting/instance_methods.rb:31:in `load_from_draft'
  drafting (0.2.0) lib/drafting/class_methods.rb:8:in `from_draft'
  drafting (0.2.0) lib/drafting/draft.rb:8:in `restore'
  app/controllers/api/community/company_documents_controller.rb:194:in `check_for_existing_draft'
  actionpack (4.2.9) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.9) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.9) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.9) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.9) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.9) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.9) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.9) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.9) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.9) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.9) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.9) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.9) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.9) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.9) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.9) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.9) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.9) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.9) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.9) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.9) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.9) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.9) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.9) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.9) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.9) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.9) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.9) lib/action_dispatch/routing/route_set.rb:817:in `call'
  apipie-rails (0.3.4) lib/apipie/static_dispatcher.rb:65:in `call'
   () home/amit/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/omnicontacts-64a50f77ad67/lib/omnicontacts/middleware/base_oauth.rb:43:in `call'
   () home/amit/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/omnicontacts-64a50f77ad67/lib/omnicontacts/middleware/base_oauth.rb:43:in `call'
   () home/amit/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/omnicontacts-64a50f77ad67/lib/omnicontacts/middleware/base_oauth.rb:43:in `call'
   () home/amit/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/omnicontacts-64a50f77ad67/lib/omnicontacts/builder.rb:28:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  bullet (4.14.5) lib/bullet/rack.rb:12:in `call'
  apipie-rails (0.3.4) lib/apipie/extractor/recorder.rb:132:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (1.6.8) lib/rack/etag.rb:24:in `call'
  rack (1.6.8) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.8) lib/rack/head.rb:13:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.9) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.9) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  neo4j (9.1.2) lib/neo4j/migrations/check_pending.rb:16:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.9) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.9) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.9) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.9) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.9) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.9) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.9) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.9) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.9) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.9) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.2.1) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  rack (1.6.8) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.9) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.9) lib/rails/engine.rb:518:in `call'
  railties (4.2.9) lib/rails/application.rb:165:in `call'
  rack (1.6.8) lib/rack/content_length.rb:15:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.9.1) lib/eventmachine.rb:193:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.6.8) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.8) lib/rack/server.rb:287:in `start'
  railties (4.2.9) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.9) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.9) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.9) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.9) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'

How can I resolve this issue

**Comment by ledermann** [comment]
Seems like a marshalling issue. Can't reproduce it here. Can you post the database schema of your drafted model? Maybe there is a field type the gem can not handle (yet).

**Comment by crisanjo** [comment]
I have the same problem, is there any solution?
